services:
  - type: web
    name: indian-legal-copilot-api

    runtime: docker

    plan: free

    healthCheckPath: /health

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: MODEL_NAME
        value: llama-3.3-70b-versatile

      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2

      - key: TOP_K
        value: 10

      - key: FAISS_INDEX_PATH
        value: vectorstore/faiss_index